apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: setup-harvester-clusters
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - "/vmnetwork"
    - "/vmimage"
    - "/keypair"
    - "/cloudinit"
    - "/simple"
  repo: https://github.com/harvester/harvester-fleet-examples
